package com.ughen.mapper;

import com.ughen.model.db.FrameTest;
import com.ughen.model.db.FrameTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FrameTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uz_frame_test
     *
     * @mbggenerated
     */
    int countByExample(FrameTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uz_frame_test
     *
     * @mbggenerated
     */
    int deleteByExample(FrameTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uz_frame_test
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uz_frame_test
     *
     * @mbggenerated
     */
    int insert(FrameTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uz_frame_test
     *
     * @mbggenerated
     */
    int insertSelective(FrameTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uz_frame_test
     *
     * @mbggenerated
     */
    List<FrameTest> selectByExample(FrameTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uz_frame_test
     *
     * @mbggenerated
     */
    FrameTest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uz_frame_test
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FrameTest record, @Param("example") FrameTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uz_frame_test
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FrameTest record, @Param("example") FrameTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uz_frame_test
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FrameTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uz_frame_test
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FrameTest record);
}