package com.ughen.model.db;

import java.util.Date;

public class FrameTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uz_frame_test.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uz_frame_test.test_date
     *
     * @mbggenerated
     */
    private Date testDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uz_frame_test.test_info
     *
     * @mbggenerated
     */
    private String testInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uz_frame_test.ID
     *
     * @return the value of uz_frame_test.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uz_frame_test.ID
     *
     * @param id the value for uz_frame_test.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uz_frame_test.test_date
     *
     * @return the value of uz_frame_test.test_date
     *
     * @mbggenerated
     */
    public Date getTestDate() {
        return testDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uz_frame_test.test_date
     *
     * @param testDate the value for uz_frame_test.test_date
     *
     * @mbggenerated
     */
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uz_frame_test.test_info
     *
     * @return the value of uz_frame_test.test_info
     *
     * @mbggenerated
     */
    public String getTestInfo() {
        return testInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uz_frame_test.test_info
     *
     * @param testInfo the value for uz_frame_test.test_info
     *
     * @mbggenerated
     */
    public void setTestInfo(String testInfo) {
        this.testInfo = testInfo == null ? null : testInfo.trim();
    }
}